services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      # Number of workers - adjust to your needs
      replicas: 1
    restart: unless-stopped
    env_file:
      - .env
  playwright:
    image: mcr.microsoft.com/playwright:v1.50.1-noble
    network_mode: host
    # You can change port of playwright API here
    command: /bin/sh -c "npx -y playwright@1.50.1 run-server --port 3000 --host 0.0.0.0"
    restart: unless-stopped
